# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: imakiba
google_analytics: UA-40992007-1

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: IMAKIBA

description: 李航的blog
author:
  name: IMAKIBA
  #email: lengyue524@gmail.com
  github: lengyue524
  twitter: lengyue524
#  pinterest: asd123
#  linkedin: asd123
  bio: Welcom to my blog!
  email_md5: 43ee7f8f8ce022f53e3a2807f1ab7ada
  resume: /%E7%AE%80%E5%8E%86/2015/01/01/resume.html

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
